version: 2
updates:

  - package-ecosystem: "maven"
    directory: "."
    open-pull-requests-limit: 10
    ignore:
      - update-types: ["version-update:semver-major"]
        dependency-name: "*"
    schedule:
      interval: "monthly"
      day: "monday"
