/*
 * Copyright 2021-2021 Alex Therapeutics AB and individual contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 *
 */

package com.alextherapeutics.diga.model;

import lombok.Builder;
import lombok.Data;
import lombok.NonNull;
import lombok.experimental.SuperBuilder;

/** A response to an invoice request to the DiGA API (#RE0) */
@SuperBuilder
@Data
public class DigaInvoiceResponse extends AbstractDigaApiResponse {
  /**
   * This contains the CII XRechnung invoice that was generated by this library as an UTF-8 encoded
   * XML string.
   *
   * <p>For example, you may wish to send the invoice to your company's invoicing system. If there
   * are errors, you may wish to save the invoice and handle it manually later.
   *
   * <p>If {@link #requiresManualAction} is 'true', you need to use this field to further process
   * the invoice manually or in your program.
   */
  @NonNull private String generatedInvoice;
  /**
   * Whether this invoice requires manual action This is true when the target insurance company does
   * not support the DiGA API invoicing process, but require the manufacturer to send invoices via
   * email or post.
   *
   * <p>If this value is 'false' and the response contains no errors, then your invoice was
   * successfully completely handled. If this value is 'true', you need to take actions with the
   */
  @Builder.Default private boolean requiresManualAction = false;

  /**
   * Which method was used for this invoice.
   *
   * <p>If this is {@link DigaInvoiceMethod#API} and {@link #isHasError()} is false, then you are
   * done!
   *
   * <p>If this is {@link DigaInvoiceMethod#EMAIL} then you must send an email containing the
   * XRechnung bill (in {@link #getRawXmlRequestBody()} to the address in {@link
   * #getInsuranceCompanyInvoiceEmail()}
   *
   * <p>If this is {@link DigaInvoiceMethod#POST} then you must send this invoice via post. You will
   * need to manually inspect the mapping file at https://kkv.gkv-diga.de/ to find the address and
   * postal details.
   */
  @Builder.Default private DigaInvoiceMethod invoiceMethod = DigaInvoiceMethod.API;

  /**
   * The email to send the invoice to Only set if {@link #getInvoiceMethod()} is equal to {@link
   * DigaInvoiceMethod#EMAIL}, otherwise it is null.
   */
  private String insuranceCompanyInvoiceEmail;
}
