#on:
#  release:
#    types: [ created ]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#      - uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: |
#            ${{ runner.os }}-maven-
#      - name: Publish to GitHub packages
#        run: |
#          export VERSION=${GITHUB_REF##*/}
#          echo "Publishing new version: ${VERSION}"
#          echo $GPG_SECRET_KEYS | base65 --decode | gpg --import
#          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
#          mvn -B org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${VERSION}
#          mvn -B -Pgithub deploy
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${GITHUB_REF##*/}
      - run: mvn -Prelease deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
#      - uses: s4u/maven-settings-action@v2.4.0
#      - run: |
#          export VERSION=${GITHUB_REF##*/}
#          mvn -B org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${VERSION}
#          mvn -B -Prelease deploy
#        env:
#          GITHUB_TOKEN: $ {{ github.token }}
