on:
  release:
    types: [ created ]

jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto
          cache: maven
      - run: mvn org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${GITHUB_REF##*/}
      - run: mvn -Prelease deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
